### ISSUE TITLE
I don't understand how will be program is work

### ISSUE THREAD

**Issue by deadcxap** [kurotu/OVR-Lighthouse-Manager#2]
I tried it, and I don't really understand whether steamvr should launch this program, or should I manually do it in advance? If the program window is not open, starting and stopping steamvr does not stop or start base stations. If the window is open, yes, the stations turn on and off... But why this automation if you still need to launch the program in advance?
Is it possible to make a windows service that will hang in the background and do the same job? Or minimize the program to the tray so that we can just install it into startup and it will actually work automatically?

**Comment by kurotu** [comment]
The installer should configure SteamVR to launch the lighthouse manager. So neither extra setup nor background services are needed because SteamVR automatically opens the program.

1. If the program is not opened by SteamVR, please make sure that `C:\Program Files (x86)\Steam\config\appconfig.json` contains following item:
    ```
    "C:\\Program Files\\OVR Lighthouse Manager\\manifest.vrmanifest"
    ```
    If not found, please reinstall the program.

2. If the program is launched by SteamVR but base stations are not turned on, the program possibly failed to find base stations because of some issues. I'll investigate that as related to #1.

**Comment by deadcxap** [comment]
I apologize, I was incorrectly checking the work. It turns out that if steamvr doesn't find the helmet, it won't run any additional programs. With activated virtualdesktop everything worked correctly.
However, a request for a "do not show window" mode or "keep minimized in the tray" still relevant.)

**Comment by kurotu** [comment]
I close this Issue now that the original question has been answered. I understand that there is a request to hide the window or minimize it to the tray, but this is outside the scope of this Issue.
